import { components as switchboardComponents } from '../generated/switchboard.ts';
import { components as userComponents } from '../generated/users.ts';

export type App = switchboardComponents['schemas']['App'];
export type AppAuthConfig = switchboardComponents['schemas']['AppAuthConfig'];
export type AppAuthConfigData = switchboardComponents['schemas']['AppAuthConfigData'];
export type AppAuthConfigOIDC = switchboardComponents['schemas']['AppAuthConfigOIDC'];
export type AppAuthConfigOAuth2 = switchboardComponents['schemas']['AppAuthConfigOAuth2'];
export type AppAuthConfigApiKey = switchboardComponents['schemas']['AppAuthConfigApiKey'];
export type AppAuthConfigHTTPBasicAuth = switchboardComponents['schemas']['AppAuthConfigHTTPBasicAuth'];
export type AppAuthConfigHTTPRefresh = switchboardComponents['schemas']['AppAuthConfigHTTPRefresh'];
export type AppAuthConfigCreate = switchboardComponents['schemas']['AppAuthConfigCreate'];
export type Hub = switchboardComponents['schemas']['Hub'];
export type HubBoardUsers = switchboardComponents['schemas']['HubBoardUsers'];
export type HubBoardUser = switchboardComponents['schemas']['HubBoardUser'];
export type Board = switchboardComponents['schemas']['Board'];
export type BoardCreate = switchboardComponents['schemas']['BoardCreate'];
export type HubBoardCreate = switchboardComponents['schemas']['HubBoardCreate'];
export type BoardPublishCommand = switchboardComponents['schemas']['BoardPublishCommand'];
export type BoardUnpublishCommand = switchboardComponents['schemas']['BoardUnpublishCommand'];
export type BoardPublishResult = switchboardComponents['schemas']['BoardPublishResult'];
export type BoardUnpublishResult = switchboardComponents['schemas']['BoardUnpublishResult'];
export type BoardPublishResultMessage = switchboardComponents['schemas']['BoardPublishResultMessage'];
export type BoardStatus = switchboardComponents['schemas']['BoardStatus'];
export type BoardPublishInfo = switchboardComponents['schemas']['BoardPublishInfo'];
export type BoardListener = switchboardComponents['schemas']['BoardListener'];
export type BoardsPage = switchboardComponents['schemas']['BoardsPage'];
export type HubsPage = switchboardComponents['schemas']['HubsPage'];
export type Connection = switchboardComponents['schemas']['Connection'];
export type ConnectionBoardReference = switchboardComponents['schemas']['ConnectionBoardReference'];
export type CreateConnectionRequestBody = switchboardComponents['schemas']['CreateConnectionRequestBody'];
export type UpdateConnectionRequestBody = switchboardComponents['schemas']['UpdateConnectionRequestBody'];
export type ConnectionDataAPIKey = switchboardComponents['schemas']['ConnectionDataAPIKey'];
export type ConnectionDataHTTPBasicAuth = switchboardComponents['schemas']['ConnectionDataHTTPBasicAuth'];
export type ConnectionDataSecret = switchboardComponents['schemas']['ConnectionDataSecret'];
export type ConnectionDataOAuth2ClientCredentials =
    switchboardComponents['schemas']['ConnectionDataOAuth2ClientCredentials'];
export type ConnectedAppsPage = switchboardComponents['schemas']['ConnectedAppsPage'];
export type ConnectedApp = switchboardComponents['schemas']['ConnectedApp'];
export type ConnectionOverview = switchboardComponents['schemas']['ConnectionOverview'];
export type ConnectionsPage = switchboardComponents['schemas']['ConnectionsPage'];
export type InitConnectionRequestBody = switchboardComponents['schemas']['InitConnectionRequestBody'];
export type InitConnectionResponseBody = switchboardComponents['schemas']['InitConnectionResponseBody'];
export type InitConnectionAction = switchboardComponents['schemas']['InitConnectionAction'];
export type InitConnectionActionRedirect = switchboardComponents['schemas']['InitConnectionActionRedirect'];
export type InitConnectionActionForm = switchboardComponents['schemas']['InitConnectionActionForm'];
export type SchemaSignedURLResponseBody = switchboardComponents['schemas']['SchemaSignedURLResponseBody'];
export type SignedURLResponseBody = switchboardComponents['schemas']['SignedURLResponseBody'];
export type CreateCredentialRequestBody = switchboardComponents['schemas']['CreateCredentialRequestBody'];
export type CredentialType = switchboardComponents['schemas']['CredentialType'];
export type CredentialDataOAuth2Refresh = switchboardComponents['schemas']['CredentialDataOAuth2Refresh'];
export type CredentialDataRaw = switchboardComponents['schemas']['CredentialDataRaw'];
export type CredentialDataBasicAuth = switchboardComponents['schemas']['CredentialDataBasicAuth'];
export type Server = switchboardComponents['schemas']['Server'];
export type Scopes = switchboardComponents['schemas']['Scopes'];
export type PageInfo = switchboardComponents['schemas']['PageInfo'];
export type BoardVariablesSchema = switchboardComponents['schemas']['BoardVariablesSchema'];
export type VariablesSchema = switchboardComponents['schemas']['VariablesSchema'];
export type Error = switchboardComponents['schemas']['Error'];
export type ConnectIntegration = switchboardComponents['schemas']['ConnectIntegration'];
export type HubApp = switchboardComponents['schemas']['HubApp'];
export type HubAppAuthConfig = switchboardComponents['schemas']['HubAppAuthConfig'];

// User Schema
export type User = userComponents['schemas']['User'];
