name: release
on:
  push:
    branches:
      - main
      - next
permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC for npm provenance
jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.VERSORI_RELEASER_APP_ID }}
          private-key: ${{ secrets.VERSORI_RELEASER_PRIVATE_KEY }}
      - name: Release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
