import { SdkAuthApiKey } from '@versori/sdk';

/**
 * AuthSigningKeyJwt denotes the end-user is authenticated to Versori using a JWT signed by a signing key
 * issued to the Versori organisation.
 *
 * The `sub` claim of the JWT is used to identify the user's external ID.
 */
export type EndUserAuthSigningKeyJwt = {
    type: 'jwt';
    token: string;
};

/**
 * AuthApiKey denotes the end-user is authenticated to Versori using an API key generated by the organisation.
 *
 * WARNING: This method of authentication is not recommended in production since the API key is scoped to the whole
 * organisation and not the individual user, which would allow end-users of your application organisation-wide access
 * to your Versori account.
 */
export type EndUserAuthApiKey = SdkAuthApiKey & {
    userId: string;
};

export type EndUserAuth = EndUserAuthSigningKeyJwt | EndUserAuthApiKey;
